### ISSUE TITLE
Support TETR.IO BETA 1.2.0+

### ISSUE THREAD

**Issue by Rinrin0413** [Rinrin0413/tetr-ch-rs#15]
The new TETRA CHANNEL API documentation has been published:
https://tetr.io/about/api

## ToDo

- [x] Conform to the new Server Statistics endpoint. [#16]
- [x] Conform to the new Server Activity endpoint. [23a3d17d578a5c139caaf1b0b8395e15117ddd6f]
- [x] Conform to the new User Info endpoint. [#19]
- [x] Conform to the new User Search endpoint. [#21]
- [x] Implement methods for the User Summaries endpoints.
    - [x] Implement method for the 40 LINES endpoint. [#23]
    - [x] Implement method for the BLITZ endpoint. [#25]
    - [x] Implement method for the QUICK PLAY endpoint. [#27]
    - [x] Implement method for the EXPERT QUICK PLAY endpoint. [#29]
    - [x] Implement method for the TETRA LEAGUE endpoint. [#31]
    - [x] Implement method for the ZEN endpoint. [#33]
    - [x] Implement method for the Achievements endpoint. [#35]
    - [x] Implement method for the "All" endpoint. [#37]
- [x] Implement method for the User Leaderboard endpoint. [#39]
- [x] Implement method for the Historical User Leaderboard endpoint. [#41]
- [x] Implement method for the User Personal Records endpoint. [#43]
- [x] Implement method for the Records Leaderboard endpoint. [#45]
- [x] Implement method for the Record Search endpoint. [#47]
    - [x] Implement `SearchedRecordResponse` struct. [#71]
- [x] Support the new TETRA NEWS endpoints.
    - [x] Implement method for the "All Latest News" endpoint. [#49]
    - [x] Conform to the new Latest News endpoint. [#51]
- [x] Implement methods for the Labs endpoints.
    - [x] Implement method for the Labs Scoreflow endpoint. [#53]
    - [x] Implement method for the Labs Leagueflow endpoint. [#55]
    - [x] Implement method for the Labs League Ranks endpoint. [#57]
- [x] Implement method for the Achievement Info endpoint. [#59]
- [x] Add the new rank X+. [#61]
- [x] Remove the elements for the discontinued endpoints. [#64]
- [x] Improve the structures of the files and elements. [#63]
- [x] Implement some useful methods for the models. [#67]
- [x] Improve the documentation. [#69]
- [x] Conform to the new error response structure. [#84]
- [x] Fix some problems.
    - [x] The `RecordsLeaderboardId::to_param` method ignores its `revolution_id` field. [#73]
    - [x] Write missing "Panics" sections in some documentations. [#77]
    - [x] Make some fields of the `PartialLeagueData` struct optional. [21deaabfa0dbf3a09300b3bd35de0a6c8d141595]
    - [x] Make the `SearchCriteria::init` methods are working. [f90cbc1528187c661d84823bf713af30a8ad32e0]
- [x] Final adjustments to this library.
    - [x] Make the option in the `Client::get_news_all` method mandatory. [#75]
    - [x] Improve the panic handling. [#79]
    - [x] Make a deserialization be tried before returning a HTTP error. [#82]
    - [x] Improve the argument documentation for consistency. [66b297317d267541612654b3730f58283491f6a9]
    - [x] Mark the color constants for the XX rank as deprecated. [b361c0fb6faee7cb1613b07b5fb7559ed52f15c7]
    - [x] Make the optional boolean fields in the models completely boolean. [#87]
    - [x] Make the enumerators of the `ResponseError` enum have appropriate error types. [#89]
    - [x] Mention about the exceptions in the API responses in the documentation. [04aed5a5482ed401a675f9433b67ae66a91bdb69]
    - [x] Add re-exports in the `model::util` module. [0ead1ddb845bbec674e1176d06292f2b8f4f3d24, 8da2a1c4a4f2a85534fa3daca8d0abed48ead15d]
    - [x] Add `model::prelude` module. [96fc77b3af94749824d013c8c85b1ad53d97822d, eba32368eaa353c7e9c92fd3af1036aa6f1eee27]
    - [x] Add `crate::prelude` module. [28739dbee7da3d57b4b7379383df25fbc63ceff9, 14dc0d6039b276a227da8aa0980a4b32ae35fdad, 47626a80bb4e3b1b6640598c874c4835ffbb0757]
    - [x] Indent the next lines in the lists in the documentation. [#15]
    - [x] Add derive `Clone` and `Debug` for some types for parameters. [64f9ac77e8b8e5cba037cad61923dace2c34f5e7]
    - [x] Add URL encodings. [21443e422fc83e8c421c6a363a37abeb24ba736f]
- [x] Rename some models to appropriate names. [#91]
- [x] Provide additional utility types. [#93]
- [x] Implement some methods of the models with macros. [#95]
- [x] Add support for `X-Session-ID`. [#97]
    - [x] Make the `Client` struct reusable. [ed10aef00d430c3fda8fb08ccb46d289f6701a55]
- [x] Update the examples. [#81]
- [x] Update the READMEs. (`README.md` and `src/lib.rs`) [b76b8e485cf19b42393d5980b14d356d815ab230]
